version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork


  server:
    build:
      context: ./server
    ports:
      - "${PORT}:8000"
    networks:
      - mynetwork
networks:
  mynetwork: